# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase_Analytics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'

  # Pods for Firebase_Analytics

end
